# Generated by Django 3.2.6 on 2021-08-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.TextField(verbose_name='Кнопка в меню')),
            ],
            options={
                'verbose_name': 'Кнопки в меню бота',
                'verbose_name_plural': 'Кнопки в меню бота',
            },
        ),
        migrations.CreateModel(
            name='Message_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщения бота',
                'verbose_name_plural': 'Сообщения бота',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
