# Generated by Django 3.2.6 on 2021-08-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210814_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(1, 'Не купил'), (2, 'Обычный клиент'), (3, 'Постоянный клиент'), (4, 'Оптовик 1'), (5, 'Оптовик 2')], null=True, verbose_name='Уровень клиента'),
        ),
    ]
