# Generated by Django 3.2.6 on 2021-08-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_product_сat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
