# Generated by Django 3.2.6 on 2021-08-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_file_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data_kol',
            field=models.IntegerField(default=0, verbose_name='Количество загруженных данных'),
        ),
    ]
