# Generated by Django 3.2.6 on 2021-08-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_order_data_kol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_order',
            name='file_order',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Загружаемые данные'),
        ),
        migrations.AlterField(
            model_name='order',
            name='step',
            field=models.IntegerField(choices=[(1, 'Клиент вводит данные'), (2, 'Клиент не оплатил'), (3, 'Обрабатывается менеджером'), (4, 'Успешно доставлено'), (5, 'Отменен')], verbose_name='Статус заказа'),
        ),
    ]
