# Generated by Django 3.2.6 on 2021-08-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20210816_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='image/', verbose_name='Изображение товара'),
        ),
    ]
