# Generated by Django 3.2.6 on 2021-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.TextField(default='', null=True, verbose_name='Код для платежа'),
        ),
        migrations.AlterField(
            model_name='file_order',
            name='file_order',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='Загружаемые данные'),
        ),
        migrations.AlterField(
            model_name='order',
            name='data_have',
            field=models.TextField(default='', null=True, verbose_name='Введенные данные пользователем'),
        ),
    ]
