# Generated by Django 3.2.6 on 2021-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20210816_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
    ]
