# Generated by Django 3.2.6 on 2021-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ask',
            field=models.TextField(null=True, verbose_name="Вопросы к товару (разделение на отдельные сообщения ';')"),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_product',
            field=models.IntegerField(null=True, verbose_name='Id продукта, который просматривает'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kol_ask',
            field=models.IntegerField(null=True, verbose_name='Количество отвеченных вопросов'),
        ),
    ]
