# Generated by Django 3.2.6 on 2021-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20210818_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_product',
            field=models.IntegerField(default=-1, null=True, verbose_name='Id продукта, который просматривает'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kol_ask',
            field=models.IntegerField(default=-1, null=True, verbose_name='Количество отвеченных вопросов'),
        ),
    ]
