# Generated by Django 3.2.6 on 2021-08-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_auto_20210818_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nesting_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='nesting_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_category', to='bot.category'),
        ),
    ]
