# Generated by Django 3.2.6 on 2021-08-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_auto_20210818_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nesting_level',
            field=models.IntegerField(default=1, verbose_name='Вложенный уровень'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_category', to='bot.category', verbose_name='Родитель'),
        ),
    ]
